### ISSUE TITLE
update or new version using LVGL V9?

### ISSUE THREAD

**Issue by jingaworks** [limpens/esp32-8048S043#3]
Thank you for your code,

I use it and start my project based on your code.

Now that LVGL V9 is out, I wanted to start to use it, but it is over my head to make the needed changes to adapt it to V9.

Can you please make a new version of this script using LVGL V9? 

Thank you very much for the provided code, it's a great starting point for someone like me.

**Comment by limpens** [comment]
Added a version for lvgl 9 here: https://github.com/limpens/esp32-8048S043-lvgl9
