### ISSUE TITLE
runtime error 

### ISSUE THREAD

**Issue by baza1978** [limpens/esp32-8048S043#4]
board esp32-8048S043
SPRAM enabled

тРЫ[0;32mI (970) display: Register display driver to LVGLтРЫ[0m

assert failed: xQueueSemaphoreTake IDF\components\freertos\FreeRTOS-Kernel\queue.c:1653 (( pxQueue ))

Backtrace: 0x40376952:0x3fca3000 0x4037b53d:0x3fca3020 0x40381701:0x3fca3040 0x4037bc1a:0x3fca3160 0x42001bd6:0x3fca31a0 0x42001f5b:0x3fca31c0 0x42001b7a:0x3fca31e0 0x4037ddec:0x3fca3210 0x4037d9e5:0x3fca3240

**Comment by baza1978** [comment]
PLATFORM: Espressif 32 (6.5.0) > esp32-8048S043C
HARDWARE: ESP32S3 240MHz, 320KB RAM, 16MB Flash

**Comment by limpens** [comment]
Please check the lvgl 9 version: https://github.com/limpens/esp32-8048S043-lvgl9
Semaphore has been removed in this version.
