### ISSUE TITLE
How to compile the code and upload it to the board ?

### ISSUE THREAD

**Issue by eagl1** [limpens/esp32-8048S043#5]
Hi,

I have this display board and trying to find its C/C++ source code to embed it in arduino famous tft library `TFT_eSPI`.

But couldn't find a working arduino code, all working codes are done through platformio.

I downloaded your code but don't know how to compile the code and upload it to the board.

**Comment by limpens** [comment]
This is a project for [esp-idf](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/get-started/index.html), using this with Arduino code might be difficult.


Edit: [This project ](https://github.com/rzeldent/esp32-smartdisplay)does use Arduino, but is also using platformio. Perhaps easier than the esp-idf route.

**Comment by eagl1** [comment]
Yes I know smart display platformio project I worked on it and got it to work.

I just want to learn how to know the init source code for the ST7262 because I want to use it in a pure arduino code without lvgl library.
